    <div class="container-fluid"> 
     <div class="container">    
      <div class="row">    
        
        <div class="col-sm-4" style="background-color:lavender";>
            <form action="" method="post">  
                <p>
                    <b>Códigos do Jogo:</b>
                        <img src="Imagem/codigos.gif"/>
                </p> 
                <input type="text" name="valor" value="">
                <button class="buttonA buttonA1">Seguir</button>
                        <br>
             </form>
        </div>
           
        <div class="col-sm-4" style="background-color:lavenderblush;">
           
            <form action="" method="post">  
                <p>    <b>Action The Game</b> 
                        <img src="Imagem/perso/lvs/sowrdGIF.gif" />
                </p> 
                <input type="text" name="valor" value="">
                <button class="buttonA buttonA1">Seguir</button>
                        <br>
             </form>
             
        </div>
        
        <div class="col-sm-4" style="background-color:lavender";>
            <?php include ('inc/teletransporte.inc'); ?>
        </div>
         
      </div> 
     </div>
    </div>