<?php   

       echo '<div class="center">
                    <div class="row ">
                        <!-- Logo -->
                        <div id="logo">
                            <a href="index.html" title="">
                                <img src="Imagem/logo.gif" alt="Logo" />
                            </a>
                        </div>
                        <!-- End Logo -->
                    </div>
                </div>

            <img src="Imagem/barrr.jpg" />'                              
          
?>